/**
 * Strings for the signed-in area. `SHELL_COPY` is customer-facing and follows the same vocabulary rule as `COPY`
 * (no internal or technical terms; tests/web/shell-copy.test.ts checks it). `STAFF_COPY` is for RelayPay's own staff
 * and may use staff vocabulary, which is why it is kept apart.
 */
export const SHELL_COPY = {
  brand: 'RelayPay',
  signIn: {
    title: 'Sign in to RelayPay',
    intro: 'Use your RelayPay account to see your payments and get help.',
    email: 'Email address',
    password: 'Password',
    submit: 'Sign in',
    submitting: 'Signing in…',
    invalid: 'That email address or password is not right. Please check them and try again.',
    tooMany: 'Too many attempts. Please wait a few minutes and try again.',
    unavailable: 'We could not sign you in just now. Please try again in a moment.',
    emailRequired: 'Enter your email address.',
    passwordRequired: 'Enter your password.',
  },
  nav: {
    label: 'Main',
    dashboard: 'Overview',
    payments: 'Payments',
    payouts: 'Payouts',
    invoices: 'Invoices',
    support: 'Support',
    settings: 'Settings',
    signOut: 'Sign out',
    skip: 'Skip to main content',
  },
  overview: {
    title: 'Overview',
    paymentsCard: 'Payments',
    payoutsCard: 'Payouts',
    invoicesCard: 'Invoices',
    recent: 'Recent activity',
    recentEmpty: 'No activity yet.',
    support: 'Need help?',
    supportBody: 'Talk to RelayPay Support about a payment, a payout or your account.',
    supportAction: 'Start a conversation',
    conversations: 'Your recent conversations',
    conversationsEmpty: 'You have not talked to RelayPay Support yet.',
    viewAll: 'View all',
  },
  lists: {
    payments: { title: 'Payments', empty: 'No payments yet.' },
    payouts: { title: 'Payouts', empty: 'No payouts yet.' },
    invoices: { title: 'Invoices', empty: 'No invoices yet.' },
    columns: {
      reference: 'Reference',
      date: 'Date',
      amount: 'Amount',
      status: 'Status',
      type: 'Type',
      recipient: 'Recipient',
    },
  },
  support: {
    title: 'RelayPay Support',
    transcriptTitle: 'Conversation',
    transcriptEmpty: 'Nothing was said in this conversation.',
    back: 'Back to overview',
    you: 'You',
    support: 'RelayPay Support',
    ticket: 'Reference',
  },
  settings: {
    title: 'Settings',
    profile: 'Your details',
    name: 'Name',
    email: 'Email address',
    company: 'Company',
    plan: 'Plan',
    signOutHint: 'Signing out ends your session on this device.',
  },
  human: {
    title: 'Chat with a support specialist',
    waiting: 'A specialist will join shortly. You can write your message below while you wait.',
    labelYou: 'You',
    labelSpecialist: 'Support specialist',
    labelSystem: 'RelayPay Support',
    typing: '{name} is typing…',
    typingGeneric: 'A specialist is typing…',
    messageLabel: 'Your message',
    placeholder: 'Type your message',
    send: 'Send',
    sending: 'Sending…',
    logLabel: 'Conversation with a support specialist',
    tooLong: 'Messages can be up to 2,000 characters.',
    sendFailed: 'Your message could not be sent. Please try again.',
    rateLimited: 'You are sending messages very quickly. Please wait a moment.',
    closedTitle: 'This conversation is closed',
    closedBody: 'Your conversation with RelayPay Support has ended. You can start a new conversation whenever you need help.',
    closedAction: 'Back to overview',
    trouble: "We're having trouble updating this conversation. We'll keep trying.",
    banner: 'You have an open conversation with a support specialist.',
    bannerAction: 'Continue',
  },
  notFound: {
    title: 'We could not find that',
    body: 'It may not exist, or it may belong to a different account.',
    action: 'Back to overview',
  },
} as const;

export const STAFF_COPY = {
  brand: 'RelayPay Support Desk',
  nav: {
    label: 'Staff',
    queue: 'Queue',
    conversations: 'Conversations',
    signOut: 'Sign out',
    skip: 'Skip to main content',
  },
  queue: {
    title: 'Support queue',
    open: 'Open',
    waiting: 'Waiting for staff',
    inProgress: 'In progress',
    escalated: 'Escalated',
    resolvedToday: 'Resolved today',
    empty: 'No conversations to show.',
    columns: { customer: 'Customer', issue: 'Issue', status: 'Status', started: 'Started', ticket: 'Ticket' },
  },
  conversations: { title: 'Conversations', empty: 'No conversations yet.' },
  chat: {
    title: 'Text chat',
    voiceTranscript: 'Voice conversation',
    waiting: 'Waiting for staff. Take this conversation to reply.',
    assignedTo: 'Assigned to {name}',
    assignedToYou: 'Assigned to you',
    take: 'Take this conversation',
    taken: 'Another team member has taken this conversation.',
    close: 'Close conversation',
    confirmClose: 'Close it now',
    cancel: 'Keep open',
    closed: 'This conversation is closed.',
    replyLabel: 'Reply to the customer',
    send: 'Send',
    sending: 'Sending…',
    customerTyping: 'Customer is typing…',
    customer: 'Customer',
    staffYou: 'You',
    system: 'System',
    notAllowed: 'Only the assigned team member or an admin can reply.',
    tooLong: 'Messages can be up to 2,000 characters.',
    sendFailed: 'The message could not be sent. Try again.',
    rateLimited: 'You are sending messages very quickly. Wait a moment.',
    trouble: 'Connection problem. Retrying.',
  },
  detail: {
    title: 'Conversation',
    transcript: 'Transcript',
    transcriptEmpty: 'No turns recorded.',
    customer: 'Customer',
    ticket: 'Ticket',
    escalation: 'Escalation',
    callback: 'Callback request',
    unlinked: 'Not linked to a customer account',
    back: 'Back to conversations',
    notFound: 'Conversation not found, or not available to you.',
  },
} as const;

/** Every string of an object tree, for the vocabulary test. */
export function allStrings(tree: unknown): string[] {
  if (typeof tree === 'string') return [tree];
  if (tree && typeof tree === 'object') return Object.values(tree).flatMap(allStrings);
  return [];
}
