/**
 * Strings for the signed-in area. `SHELL_COPY` is customer-facing and follows the same vocabulary rule as `COPY`
 * (no internal or technical terms; tests/web/shell-copy.test.ts checks it). `STAFF_COPY` is for RelayPay's own staff
 * and may use staff vocabulary, which is why it is kept apart.
 */
export const SHELL_COPY = {
  brand: 'RelayPay',
  signIn: {
    title: 'Sign in to RelayPay',
    intro: 'Use your RelayPay account to see your payments and get help.',
    email: 'Email address',
    password: 'Password',
    submit: 'Sign in',
    submitting: 'Signing in…',
    invalid: 'That email address or password is not right. Please check them and try again.',
    tooMany: 'Too many attempts. Please wait a few minutes and try again.',
    unavailable: 'We could not sign you in just now. Please try again in a moment.',
    emailRequired: 'Enter your email address.',
    passwordRequired: 'Enter your password.',
  },
  nav: {
    label: 'Main',
    dashboard: 'Overview',
    payments: 'Payments',
    payouts: 'Payouts',
    invoices: 'Invoices',
    support: 'Support',
    history: 'Conversations',
    settings: 'Settings',
    signOut: 'Sign out',
    skip: 'Skip to main content',
  },
  overview: {
    title: 'Overview',
    paymentsCard: 'Payments',
    payoutsCard: 'Payouts',
    invoicesCard: 'Invoices',
    recent: 'Recent activity',
    recentEmpty: 'No activity yet.',
    support: 'Need help?',
    supportBody: 'Talk to RelayPay Support about a payment, a payout or your account.',
    supportAction: 'Start a conversation',
    conversations: 'Your recent conversations',
    conversationsEmpty: 'You have not talked to RelayPay Support yet.',
    viewAll: 'View all',
  },
  history: {
    title: 'Your conversations',
    intro: 'Every conversation you have had with RelayPay Support. Open one to read it back.',
    empty: 'You have not talked to RelayPay Support yet.',
    started: 'Started',
    outcome: 'Outcome',
    open: 'Open',
    newer: 'Newer',
    older: 'Older',
    page: 'Page {page}',
    back: 'Back to overview',
  },
  feedback: {
    aiTitle: 'How was your conversation?',
    humanTitle: 'How was the help from our support specialist?',
    optional: 'Optional. It does not change anything about your request.',
    group: 'Your rating',
    star: 'Rate {n} out of 5',
    commentLabel: 'Anything you would like to add? (optional)',
    submit: 'Send feedback',
    submitting: 'Sending…',
    skip: 'Skip',
    thanks: 'Thank you for your feedback.',
    failed: "We couldn't send your feedback. You can try again or skip.",
    needRating: 'Choose a rating first.',
  },
  lists: {
    payments: { title: 'Payments', empty: 'No payments yet.' },
    payouts: { title: 'Payouts', empty: 'No payouts yet.' },
    invoices: { title: 'Invoices', empty: 'No invoices yet.' },
    columns: {
      reference: 'Reference',
      date: 'Date',
      amount: 'Amount',
      status: 'Status',
      type: 'Type',
      recipient: 'Recipient',
    },
  },
  support: {
    title: 'RelayPay Support',
    transcriptTitle: 'Conversation',
    transcriptEmpty: 'Nothing was said in this conversation.',
    back: 'Back to overview',
    you: 'You',
    support: 'RelayPay Support',
    ticket: 'Reference',
  },
  settings: {
    title: 'Settings',
    profile: 'Your details',
    name: 'Name',
    email: 'Email address',
    company: 'Company',
    plan: 'Plan',
    signOutHint: 'Signing out ends your session on this device.',
  },
  human: {
    title: 'Chat with a support specialist',
    waiting: 'A specialist will join shortly. You can write your message below while you wait.',
    labelYou: 'You',
    labelSpecialist: 'Support specialist',
    labelSystem: 'RelayPay Support',
    typing: '{name} is typing…',
    typingGeneric: 'A specialist is typing…',
    messageLabel: 'Your message',
    placeholder: 'Type your message',
    send: 'Send',
    sending: 'Sending…',
    logLabel: 'Conversation with a support specialist',
    tooLong: 'Messages can be up to 2,000 characters.',
    sendFailed: 'Your message could not be sent. Please try again.',
    rateLimited: 'You are sending messages very quickly. Please wait a moment.',
    closedTitle: 'This conversation is closed',
    closedBody: 'Your conversation with RelayPay Support has ended. You can start a new conversation whenever you need help.',
    closedAction: 'Back to overview',
    trouble: "We're having trouble updating this conversation. We'll keep trying.",
    sendingLabel: 'Sending…',
    notSent: 'Not sent.',
    retry: 'Try again',
    remove: 'Remove',
    seen: 'Seen',
    newMessage: 'New message from {name}',
    newMessageGeneric: 'New message from your support specialist',
    waitingOnline: 'A specialist is online and will join you shortly.',
    waitingOffline: 'Our team will reply as soon as someone is free. If you would rather have a callback, tell us a day and time in the message box.',
    waitingOfflineNoCallback: 'Our team will reply as soon as someone is free.',
    waited: 'Waiting for {time}',
    stillWaiting: 'Still waiting? Tell us in the message box when you would like a callback and we will arrange it.',
    stillWaitingNoCallback: 'Thanks for your patience. Someone will be with you as soon as they can.',
    endChat: 'End chat',
    endConfirm: 'End this chat',
    endKeep: 'Keep chatting',
    endFailed: 'We could not end the chat. Please try again.',
    banner: 'You have an open conversation with a support specialist.',
    bannerAction: 'Continue',
  },
  notFound: {
    title: 'We could not find that',
    body: 'It may not exist, or it may belong to a different account.',
    action: 'Back to overview',
  },
} as const;

export const STAFF_COPY = {
  brand: 'RelayPay Support Desk',
  nav: {
    label: 'Staff',
    queue: 'Queue',
    conversations: 'Conversations',
    settings: 'Settings',
    signOut: 'Sign out',
    skip: 'Skip to main content',
  },
  queue: {
    title: 'Support queue',
    open: 'Open',
    waiting: 'Waiting for staff',
    inProgress: 'In progress',
    escalated: 'Escalated',
    resolvedToday: 'Conversations resolved today',
    empty: 'No conversations to show.',
    columns: {
      customer: 'Customer',
      issue: 'Issue',
      status: 'Status',
      started: 'Started',
      ticket: 'Ticket',
      waiting: 'Waiting',
      cost: 'Est. cost',
    },
    todayCost: 'Estimated cost today',
    todayCostNote: 'Estimated model cost for conversations started today (UTC). Not a bill.',
    costUnknown: 'Not available',
    unread: 'New messages',
    mine: 'Yours',
    newWaiting: 'A new conversation is waiting',
    trouble: 'Connection problem. The queue will update when it is back.',
    waitingNav: '{count} waiting',
  },
  conversations: { title: 'Conversations', empty: 'No conversations yet.' },
  settings: {
    title: 'Settings',
    intro: 'Choose which ways of reaching a person the support assistant offers to customers.',
    groupLegend: 'Ways to reach a person',
    status: { on: 'On', off: 'Off', soon: 'Not available yet' },
    textChat: {
      label: 'Live text chat',
      help: 'Customers who are signed in can chat in writing with a member of staff. The assistant ends the call and the conversation continues in the chat. Also needs the voice agent to have human handoff switched on.',
    },
    callback: {
      label: 'Callback request',
      help: 'The assistant collects the customer\'s name, email and a good time, and the team follows up later. Also the fallback for a customer waiting in a chat.',
    },
    phone: {
      label: 'Live phone call',
      help: 'A person taking the call live. This is not built yet, so it cannot be switched on.',
    },
    online: 'A member of staff is online now.',
    offline: 'Nobody is online now. A text chat would wait in the queue.',
    lastChanged: 'Last changed {when} by {who}.',
    neverChanged: 'Not changed yet: both are on.',
    mustKeepOne: 'Keep at least one method on, so customers always have a way to reach a person.',
    save: 'Save changes',
    saving: 'Saving…',
    saved: 'Saved. The assistant uses the new setting within a few seconds.',
    failed: 'Could not save. Try again.',
    loadFailed: 'Could not load the settings. Reload the page to try again.',
    unsaved: 'You have unsaved changes.',
    offNote: 'Customers are not offered this. Conversations already under way are not affected.',
  },
  presence: {
    label: 'Available for chats',
    on: 'Available',
    off: 'Away',
    hint: 'While you are available, customers who ask for a chat are told someone is online. Keep this page open.',
    failed: 'Could not change your availability. Try again.',
  },
  alerts: {
    group: 'Alerts',
    sound: 'Play a sound for new conversations',
    desktop: 'Show desktop notifications',
    desktopBlocked: 'Desktop notifications are blocked in this browser.',
    desktopTitle: 'RelayPay Support Desk',
  },
  chat: {
    title: 'Text chat',
    voiceTranscript: 'Voice conversation',
    waiting: 'Waiting for staff. Take this conversation to reply.',
    assignedTo: 'Assigned to {name}',
    assignedToYou: 'Assigned to you',
    take: 'Take this conversation',
    taken: 'Another team member has taken this conversation.',
    close: 'Close conversation',
    confirmClose: 'Close it now',
    cancel: 'Keep open',
    closed: 'This conversation is closed.',
    replyLabel: 'Reply to the customer',
    send: 'Send',
    sending: 'Sending…',
    customerTyping: 'Customer is typing…',
    seen: 'Seen',
    notSent: 'Not sent.',
    retry: 'Try again',
    remove: 'Remove',
    release: 'Return to queue',
    releaseConfirm: 'Return it now',
    released: 'Returned to the queue.',
    newMessage: 'New message from the customer',
    waitingSince: 'Waiting {time}',
    customer: 'Customer',
    staffYou: 'You',
    system: 'System',
    notAllowed: 'Only the assigned team member or an admin can reply.',
    tooLong: 'Messages can be up to 2,000 characters.',
    sendFailed: 'The message could not be sent. Try again.',
    rateLimited: 'You are sending messages very quickly. Wait a moment.',
    trouble: 'Connection problem. Retrying.',
  },
  detail: {
    title: 'Conversation',
    transcript: 'Transcript',
    transcriptEmpty: 'No turns recorded.',
    customer: 'Customer',
    ticket: 'Ticket',
    escalation: 'Escalation',
    callback: 'Callback request',
    unlinked: 'Not linked to a customer account',
    cost: 'Estimated cost',
    costNote: 'estimate, model usage only',
    feedback: 'Customer feedback',
    feedbackNone: 'No feedback yet',
    feedbackStages: { ai: 'Voice support', human: 'Specialist support' },
    rating: '{n} out of 5',
    back: 'Back to conversations',
    notFound: 'Conversation not found, or not available to you.',
  },
} as const;

/** Every string of an object tree, for the vocabulary test. */
export function allStrings(tree: unknown): string[] {
  if (typeof tree === 'string') return [tree];
  if (tree && typeof tree === 'object') return Object.values(tree).flatMap(allStrings);
  return [];
}
